apiVersion: apps/v1
kind: Deployment
metadata:
  name: nike-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nike-web
  template: # El template define el pod
    metadata:
      labels:
        app: nike-web
    spec:
      containers:
      - name: nike-web
        image: nike-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80