apiVersion: v1
kind: Service
metadata:
  name: nike-web-service
spec:
  type: NodePort
  selector:
    app: nike-web
  ports:
    - protocol: TCP
      port: 80        # Puerto del servicio
      targetPort: 80  # Puerto donde escucha tu contenedor